/* File: sum_clnt.c

Programmer: Mark Fienup

Date: January 21, 1998

Before compiling: rpcgen -N rsum.x and gcc -c rsum_xdr.c

"Compile" using: gcc -o sum_clnt sum_clnt.c rsum_clnt.c rsum_xdr.o -lnsl

Description: This is a client program that takes two numbers on the

command line and calls a remote server (running on chaos) using RPC

to add these numbers and compare them. */

#include <stdio.h>
#include <time.h>
#include <rpc/rpc.h>
#include "rsum.h" /* generated by rpcgen */
#define RMACHINE "chaos.cns.uni.edu"

int main(int argc, char *argv[]) { 
CLIENT *handle;
long *result;
long first;
long second;
char **str_larger;
if (argc != 3) {
fprintf(stderr, "usage: %s int int\n", argv[0]);
exit(1);
} /* end if */
handle = clnt_create(RMACHINE, RSUM_PROG,
RSUM_VERS, "tcp"); 
if (handle == NULL) {
perror("");
exit(1);
} 
/* converses command-line arguments from strings to integers */
first = atoi(argv[1]);
second = atoi(argv[2]);
/* Performs the remote procedure calls. Notice the differences from local
procedure calls: 1) include the client handle as last argument, and
2) returns a pointer to the return values */
result_sum = ADDER(first, second, handle);
result_sub = SUBER(first, second, handle);
result_mul = MULER(first, second, handle);
result_div = DIVER(first, second, handle);
printf("%d + %d = %d and the %s operand is larger\n", first, second,
*result, *str_larger);
exit(0);
} 
